[sqlalchemy] 'NoneType' object has no attribute 'get'
Note: new tests coming to handle better when connectors are off or not

Fix

Traceback (most recent call last):
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py", line 99, in decorator
    return func(*args, **kwargs)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py", line 230, in execute
    if self.interpreter.get('dialect_properties', {}).get('has_use_statement') and snippet.get('database'):
AttributeError: 'NoneType' object has no attribute 'get'
[10/Dec/2020 06:53:30 -0800] decorators   ERROR    Error running execute
Traceback (most recent call last):
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/decorators.py", line 114, in wrapper
    return f(*args, **kwargs)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/api.py", line 227, in execute
    response = _execute_notebook(request, notebook, snippet)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/api.py", line 202, in _execute_notebook
    raise ex
QueryError: 'NoneType' object has no attribute 'get'

(cherry picked from commit 32a8b39ef2e172f0b4704b1ba81553e88c186510)