[k8s] Move api into its own section
Otherwise keep hititing:

Error: UPGRADE FAILED: YAML parse error on hue/templates/ingress-https.yaml: error converting YAML to JSON: yaml: line 24: mapping values are not allowed in this context
(cherry picked from commit c633b4a8e0d40cabc2487c69962f0ba26ecb3bb6)