HUE-9073 [fs] Avoid missing user argument in _get_client_cached
File "/home/romain/projects/hue/build/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/romain/projects/hue/build/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/romain/projects/hue/build/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 178, in _get_response
    response = middleware_method(request, callback, callback_args, callback_kwargs)
  File "/home/romain/projects/hue/desktop/core/src/desktop/middleware.py", line 132, in process_view
    request.fs = fsmanager.get_filesystem(request.fs_ref)
  File "/home/romain/projects/hue/desktop/core/src/desktop/lib/fsmanager.py", line 145, in get_filesystem
    return ProxyFS(pdict, get_default_schema(), name)
  File "/home/romain/projects/hue/desktop/core/src/desktop/lib/fs/proxyfs.py", line 52, in __init__
    self._default_fs = filesystems_dict[self._default_scheme](name)
TypeError: _get_client_cached() missing 1 required positional argument: 'user'

(cherry picked from commit dc92a4aae6934a3e904fe7d29797fbe1c03deb97)

Change-Id: Id773c3fceb7bab06bcc638f24b8a1e520e290447