Install setuptools-rust
Trying to solve:

Collecting cryptography==36.0.1 (from -r /root/repo/desktop/core/requirements.txt (line 12))
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/f9/4b/1cf8e281f7ae4046a59e5e39dd7471d46db9f61bb564fddbff9084c4334f/cryptography-36.0.1.tar.gz (572kB)
    100% |████████████████████████████████| 573kB 2.8MB/s  eta 0:00:01
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-t_ad5sdt/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'

            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:

            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>