HUE-5429 [useradmin] Creating a new user gives a AttributeError: 'User' object has no attribute 'user'
(cherry picked from commit 45fd13811ecc534be8e5eef450c0a3cada67e326)