[user] Default app loading can fail
To fix:

[08/Dec/2020 11:25:16 -0800] models       ERROR    Could not load back default app
Traceback (most recent call last):
  File "/usr/share/hue/desktop/core/src/desktop/models.py", line 1768, in get_main_quick_action
    user_default_app = json.loads(user_preference.value)
AttributeError: 'dict' object has no attribute 'value'

(cherry picked from commit 42eb854867ee7a33dd9a8a26845cce8888370ae0)