HUE-7826 [security] Uncaught TypeError: privilege.privilegeScope is not a function error when deleting a Solr privilege
(cherry picked from commit 43cf9759bbf843e9fbdd28fe3d8a121059b1a917)