HUE-4364 [metastore] Handle files with carriage return in create table from a file
Hence avoid
PopupException: The headers of the file could not be removed: substring not found