[py3] Upgrade ipython module to not break the shell command
TypeError: required field "type_ignores" missing from Module
(cherry picked from commit 5caeba886a57a1bf81b881cfb459e5530017de04)