HUE-5007 [core] Get ride of bad utf8 character when doing make-locale
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd3 in position 26: invalid continuation byte
(cherry picked from commit 9f59cffcf69b29c4fc4ae59c5db4ce61c10c0cd2)