[core] Avoid failure of loading back the user starred app
Traceback (most recent call last):
  File "/hue/desktop/core/src/desktop/models.py", line 1792, in get_main_quick_action
    user_default_app = json.loads(user_preference)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
  TypeError: the JSON object must be str, bytes or bytearray, not dict

(cherry picked from commit 51535fa06923d6c2fbe8ada47bf33793d938155e)