[jwt] Bump djangorestframework-simplejwt to 5.2.0 (#2875)
- Required for error: AttributeError: 'str' object has no attribute 'decode'
- This error comes when trying to use Hue public API via Hue's JWT access token.
- Version 4.7+ contains the fix so we upgraded to the latest. This was required because we upgraded PyJWT to 2.4.0 due to CVE.

(cherry picked from commit 09999a1560978c5252662a15f57d2e5ae63b9ace)