[sqls] Avoid JSON.bigdataParse is not a function on result display
TypeError: JSON.bigdataParse is not a function
(cherry picked from commit b5349387ceabea007b120665201130fe71790bc3)