CDPD-77831: Fix JB Oozie Log Icon (#3952)
Stacktrace seen:

[07/Jan/2025 09:31:26 -0800] access       ERROR     admin - "POST /desktop/log_js_error HTTP/1.1" --- JS ERROR: {"msg":"Uncaught TypeError: lodash__WEBPACK_IMPORTED_MODULE_1___default.a.trimRight is not a function","url":"https://ccycloud-1.ni-717x-yq.root.comops.site:8889/static/desktop/js/bundles/hue/hue-bundle-651ca10da11cbc8f75e8.2537e7eff7ba.js","line":74060,"column":139,"stack":"TypeError: lodash__WEBPACK_IMPORTED_MODULE_1___default.a.trimRight is not a function\n    at app (https://ccycloud-1.ni-717x-yq.root.comops.site:8889/static/desktop/js/bundles/hue/hue-bundle-651ca10da11cbc8f75e8.2537e7eff7ba.js:74060:139)\n    at https://ccycloud-1.ni-717x-yq.root.comops.site:8889/static/desktop/js/bundles/hue/vendors~hue-chunk-651ca10da11cbc8f75e8.04f0b70fc23d.js:83803:52\n    at nextEnter (https://ccycloud-1.ni-717x-yq.root.comops.site:8889/static/desktop/js/bundles/hue/vendors~hue-chunk-651ca10da11cbc8f75e8.04f0b70fc23d.js:83627:7)\n    at https://ccycloud-1.ni-717x-yq.root.comops.site:8889/static/desktop/js/bundles/hue/vendors~hue-chunk-651ca10da11cbc8f75e8.04f0b70fc23d.js:83804:7\n    at nextEnter (https://ccycloud-1.ni-717x-yq.root.comops.site:8889/static/desktop/js/bundles/hue/vendors~hue-chunk-651ca10da11cbc8f75e8.04f0b70fc23d.js:83627:7)\n    at https://ccycloud-1.ni-717x-yq.root.comops.site:8889/static/desktop/js/bundles/hue/vendors~hue-chunk-651ca10da11cbc8f75e8.04f0b70fc23d.js:83804:7\n    at nextEnter (https://ccycloud-1.ni-717x-yq.root.comops.site:8889/static/desktop/js/bundles/hue/vendors~hue-chunk-651ca10da11cbc8f75e8.04f0b70fc23d.js:83627:7)\n    at https://ccycloud-1.ni-717x-yq.root.comops.site:8889/static/desktop/js/bundles/hue/vendors~hue-chunk-651ca10da11cbc8f75e8.04f0b70fc23d.js:83804:7\n    at nextEnter (https://ccycloud-1.ni-717x-yq.root.comops.site:8889/static/desktop/js/bundles/hue/vendors~hue-chunk-651ca10da11cbc8f75e8.04f0b70fc23d.js:83627:7)\n    at https://ccycloud-1.ni-717x-yq.root.comops.site:8889/static/desktop/js/bundles/hue/vendors~hue-chunk-651ca10da11cbc8f75e8.04f0b70fc23d.js:83804:7"}

Co-authored-by: mbalakrishnan@cloudera.com <mbalakrishnan@MacBook-Pro.local>
(cherry picked from commit 95e4e0c37eae2362a3385f7f16917c11ec7fe29a)
(cherry picked from commit d71562d2d487bd6a4e942ded6d72e37df2fd41b5)