[connector] Support connectors in Describe API
This API has an oddity on how to provide connectors for historical
reasons.

Fixing
AttributeError: 'Config' object has no attribute 'get'

(cherry picked from commit 5fe570dbef037028d3f482b724562660f9b51f33)