HUE-8737 [core] Avoid double 500 on traceback with py3
TypeError: Object of type 'FrameSummary' is not JSON serializable
(cherry picked from commit e4727ec78bffb7f10a9339ded772e7a2ccfef891)

Change-Id: I07a596b8f9000073989ff6f38ecae97d63d247ef