HUE-8737 [py3] Avoid unbound exception on Thrift connection error
Now the e object is not present anymore.
UnboundLocalError: local variable 'e' referenced before assignment

(cherry picked from commit 31aab53ba946a4c3b2198421f1d7413d2e00fb38)

Change-Id: Ia442c312e12b1b552d923e136c1601fb02c47fba