[core] Disable django admin app
It is unused anyway.

Avoids:

And

TypeError: __init__() got an unexpected keyword argument 'loaders'
Seems gone (but it might break)

ERRORS:
?: (admin.E402) 'django.contrib.auth.context_processors.auth' must be enabled in DjangoTemplates (TEMPLATES) if using the default auth backend in order to use the admin application.
?: (admin.E404) 'django.contrib.messages.context_processors.messages' must be enabled in DjangoTemplates (TEMPLATES) in order to use the admin application.
?: (admin.E406) 'django.contrib.messages' must be in INSTALLED_APPS in order to use the admin application.

https://github.com/cloudera/hue/pull/1711#issuecomment-777196647
(cherry picked from commit b4705f9f80173763695c86cc0afecd6e50a200be)