HUE-8371 [core] Shrink char field max length for Oracle DB support
While running hue migrate command, Oracle DB fails with
django.db.utils.DatabaseError: ORA-00910: specified length too long for its datatype

This fix will truncate charfield size from 2047 chars to 2000 chars.

(cherry picked from commit f85df06f4f56f52bc08e9f617f297eb370e9adc0)