GH-1807 [Django Upgrade] LDAP auth error: authenticate() missing 1 required positional argument: 'request'
(cherry picked from commit 80f8cc705b7d1a68d0a7ddc0c14cd80e0bc38448)