CDPD-56487: Initialize DB connection for the worker processes and close them when the process ends (#3317)
Internal Jira: CDPD-56487

This was tested manually in an internal cluster which exhibited the below exception when is_alive calls where initiated and while restarting/stopping the processes.

django.db.utils.OperationalError: ORA-03135: connection lost contact
django.db.utils.OperationalError: ORA-03113: end-of-file on communication channel
django.db.utils.OperationalError: ORA-03114: Not Connected to Oracle

(cherry picked from commit c0dc0b90f587032fdab205dbcdfc4ac125f43838)
(cherry picked from commit 5fcc03045afc99331bc9450a804b7bf4e6ccc2ec)
Change-Id: I2003786790fae55d075dd5dbb136d78d236956ef