Check csrf to see if it has value before setting it up (#3592)
Internal Jira: CDPD-65034

Seeing the exception:
thrift_util  ERROR    Thrift saw exception (this may be expected).
Traceback (most recent call last):
  File “/opt/cloudera/parcels/CDH-7.1.9-1.cdh7.1.9.p0.44702451/lib/hue/desktop/core/src/desktop/lib/thrift_util.py”, line 522, in wrapper
    ret = res(*args, **kwargs)
  File “/opt/cloudera/parcels/CDH-7.1.9-1.cdh7.1.9.p0.44702451/lib/hue/apps/beeswax/gen-py/TCLIService/TCLIService.py”, line 255, in decorate
    trans_client.setCustomHeaders({‘X-CSRF-TOKEN’: csrf})
TypeError: ‘NoneType’ object is not callable

and

  File “/opt/cloudera/parcels/CDH-7.1.9-1.cdh7.1.9.p0.44702451/lib/hue/desktop/core/src/desktop/lib/thrift_util.py”, line 522, in wrapper
    ret = res(*args, **kwargs)
  File “/opt/cloudera/parcels/CDH-7.1.9-1.cdh7.1.9.p0.44702451/lib/hue/apps/beeswax/gen-py/TCLIService/TCLIService.py”, line 233, in decorate
    trans_client.setCustomHeaders({‘X-Forwarded-For’: xff})
TypeError: ‘NoneType’ object is not callable

Added a task server page, tasks table. desktop document clean up works (have to move it to celery though). Need to add a django db table to store the tasks table browser

Change-Id: I464842602cf0d5daa6185ee140e47ff527f4498d

1. Added a django db table.  2. React fetches the results from this db table. 3. Added migrations scripts for the newly created task-models.py - django table

Change-Id: I955a4ed3586cc21692efe78cb25609ec3e47ff00

Working prototype of celery with file upload

(cherry picked from commit 72dff035daf0f5b6df5899d5dcf59fb41cba8ee5)

adding incomplete change

adding more changes

Adding styling changes for task browser tables and adding label/icons

Change-Id: I94ef218d686503c45889a92b55517928366ce3dc

Incomplete changes - greyout/reload file upload page, desktop_document_cleanup using redis

Change-Id: I7874f9e5b82c869ed41050fddce742e9e4d0ac97

Fixing the upload popup, the stay until all uploads are complete. Fixing document clean up install dir and duration calculation

Change-Id: I566142a8745f8756a51437cb0cd663804ab34090

Fixing S3 issue

schedule /tmp clean_up job in task_server page

Change-Id: I4e68b48dd8d112168531c1c272f285b2ff131962

Task server support ABFS fileuploads

Change-Id: I73f686afee6a2cb9720b4113079d151eebb223b5

Changing progress Filter buttons (success, failure, running) to checkboxes

Change-Id: I94395f3f360adb09fe837eb6c39b835affff8199

Task server supports Ozone fileuploads

Change-Id: Ied887a9983df7583022726cf381a8ffd6ee910d6

Celery startup script

Change-Id: If9e2af83e1620b77a8aabecff9c44827cb6bd31b

Improving Celery startup script

Change-Id: I4da8fc665ebd3b72df645e46a82b01aac997c287

Adding redis-server startup script

Change-Id: Ifaeb47a776d455b4efeeda875ac29e89459df064

Installing redis using tarball

Change-Id: I5bb471f64a40047fcab117aabddfc4ea23375183

Adding schedule upload support. Cleaned up default fallbackcomponent. Removed the csrf exempt annotations

Change-Id: I7f2be8f8dab3bbd50d3e73475d466ae4edae1a73

/tmp cleaner runs every 1000 seconds using celery-beat scheduler. Files written onto /tmp folder in the last 15 minutes wont be deleted. This time interval ensures that when a user/service is writing onto /tmp, the files are not deleted..

Change-Id: Ie84dceb383db2b873ea506b8cfdf7f5888c9be40

Adding support for killing celery tasks.

Change-Id: I19475db8222da6c3cd40bcc1eddd5f01906958c4

Restricting uploads based on free space available in /tmp and MAX_FILE_SIZE_UPLOAD_LIMIT

Change-Id: I92a1cc6d8193e256bdf22a133f1fbcb261cf9457

Redis starts with Celery. Adding celery-beat in celery startup script

Change-Id: Ifba988dc00767d16d635cf8a7a36295c0015cd7a

Adding celery beat args

Change-Id: I26c492dd97d9cb96ab0c34282829b9169a4bf403