HUE-9000 [editor] Clearing Editor history is erroring
To prevent:

Traceback (most recent call last):
  File "/home/romain/projects/hue/desktop/libs/notebook/src/notebook/decorators.py", line 111, in wrapper
    return f(*args, **kwargs)
  File "/home/romain/projects/hue/desktop/libs/notebook/src/notebook/decorators.py", line 100, in decorate
    return view_func(request, *args, **kwargs)
  File "/home/romain/projects/hue/desktop/libs/notebook/src/notebook/api.py", line 570, in clear_history
    notebook = json.loads(request.POST.get('notebook'), '{}')
TypeError: loads() takes 1 positional argument but 2 were given

(cherry picked from commit c609a98c8f15e22cb32c7dc3b0451526f07ac939)

Change-Id: I1e5ced11bf2399e1d8c1157f6e10ffa4691fdccf