[Django 3.0] ImportError: cannot import name 'curry' from 'django.utils.functional'
(cherry picked from commit 4f5058548caaced2ccd57b99b9d7212ddb6c08cf)