[shell] Upgrade ipython to not break
If not:
TypeError: required field "type_ignores" missing from Module

(cherry picked from commit 7eed6f731d642e5a970f8fd34cb872d66f5d99fa)