[Django Upgrade] ImportError: cannot import name 'render_to_response' from 'django.shortcuts'
(cherry picked from commit f9bcaec6baac63c21b231cca1c6f3d0f426152a4)