[beeswax] Integrate hive-site.xml into the Hive commands
export HIVE_CONF_DIR="/var/run/cloudera-scm-agent/process/`ls -alrt /var/run/cloudera-scm-agent/process | grep HUE | tail -1 | awk '{print $9}'`/hive-conf"

./build/env/bin/hue close_sessions 0
Closing (all=False) HiveServer2/Impala sessions older than 0 days...
Error: TCloseSessionResp(status=TStatus(errorCode=None, errorMessage=None, sqlState=None, infoMessages=None, statusCode=0))
1 sessions closed.

./build/env/bin/hue close_queries 0
Closing (all=False) HiveServer2/Impala queries older than 0 days...
/var/run/cloudera-scm-agent/process/588-hue-HUE_SERVER/hive-conf
0 queries closed.

Conflicts:

	apps/beeswax/src/beeswax/management/commands/close_sessions.py