[oozie] Don't encode request body with latin-1 for HDFS calls in Py3 for workflow shell script having Korean chars (#3159)
- For Py3 Hue, when the browser language is set to Korean and someone tries to run an oozie workflow for a shell script containing Korean chars, it was failing with the below error:

```
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 134-135: Body ('작업') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
```

- Because of i18n, the xml data is having Korean chars when the browser language is Korean which was not utf-8 encoded. So we are encoding it properly and sending the xml data as bytes instead of str type.

NOTE: This issue is not seen in Py2 Hue.

- Change the chrome browser language to Korean
- Create a new workflow with shell action
- Use any shell script with a simple "echo 안녕하세요"
- Add a workflow description in English or skip so that it takes a default description
- Submit the workflow

- E2E manual testing in Hue of a Py3 enabled cluster.

(cherry picked from commit decf994b4b1ecf69c3783afaea6f5de8f16ae405)