[api] Also lookup for query in snippet in risk call
Currently on demo.gethue:

[2021-08-28 12:04:01 +0000] [34] [DEBUG] POST /api/optimizer/query_risk/
[28/Aug/2021 05:04:01 -0700] optimizer_api ERROR    the JSON object must be str, bytes or bytearray, not 'NoneType'
Traceback (most recent call last):
  File "/usr/share/hue/desktop/libs/metadata/src/metadata/optimizer_api.py", line 60, in decorator
    return view_fn(*args, **kwargs)
  File "/usr/share/hue/desktop/libs/metadata/src/metadata/optimizer_api.py", line 200, in query_risk
    query = json.loads(request.POST.get('query'))
  File "/usr/lib/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'NoneType'

(cherry picked from commit b081f8476058e8d6c722279646dad85d01135874)