CDPD-70011: [core] Change ext-py3 package installation path (#3720)
- Giving old style file path was failing `./build/env/bin/pip freeze` with the following error:

```
harsh.gupta@Harshs-MacBook-Pro hue % ./build/env/bin/pip freeze
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/harsh.gupta/workspace/hue/upstream/hue/build/env/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/Users/harsh.gupta/workspace/hue/upstream/hue/build/env/lib/python3.8/site-packages/pip/_internal/commands/freeze.py", line 98, in run
    for line in freeze(
  File "/Users/harsh.gupta/workspace/hue/upstream/hue/build/env/lib/python3.8/site-packages/pip/_internal/operations/freeze.py", line 43, in freeze
    req = FrozenRequirement.from_dist(dist)
  File "/Users/harsh.gupta/workspace/hue/upstream/hue/build/env/lib/python3.8/site-packages/pip/_internal/operations/freeze.py", line 236, in from_dist
    editable = dist.editable
  File "/Users/harsh.gupta/workspace/hue/upstream/hue/build/env/lib/python3.8/site-packages/pip/_internal/metadata/base.py", line 338, in editable
    return bool(self.editable_project_location)
  File "/Users/harsh.gupta/workspace/hue/upstream/hue/build/env/lib/python3.8/site-packages/pip/_internal/metadata/base.py", line 179, in editable_project_location
    return url_to_path(direct_url.url)
  File "/Users/harsh.gupta/workspace/hue/upstream/hue/build/env/lib/python3.8/site-packages/pip/_internal/utils/urls.py", line 43, in url_to_path
    raise ValueError(
ValueError: non-local file URIs are not supported on this platform: 'file://Users/harsh.gupta/workspace/hue/upstream/hue/desktop/core/ext-py3/pysaml2-7.3.1'
```

- Using 2 slash file path is installing the packages + fixes the above error.

ocal setup

(cherry picked from commit 0e6025f31935d861824c125c89e7aab40d2516a4)
Change-Id: Ia2fa06a9fbab0ff95f84a4786c84023043dc8a64
(cherry picked from commit ca162a356230e5f59a78fc59156312e4691fae1a)