HUE-8888 [jb] Avoid oozie related stack trace when oozie is blacklisted
NameError: name 'OOZIE_JOBS_COUNT' is not defined
(cherry picked from commit 40a7c43d7d115739c78147895854791292388d67)

Change-Id: Id44aae268a44362fcd11f7a2a2945b04ec8684d8