[libs] Bump djangorestframework-simplejwt
Trying to avoid

  File "/usr/share/hue/build/env/lib/python3.6/site-packages/rest_framework_simplejwt/backends.py", line 43, in encode
    return token.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'

https://github.com/jazzband/djangorestframework-simplejwt/issues/326
(cherry picked from commit a455944942a6d34e4d02bd7483e7f32a512364e7)