[Django 3.0] ImportError: cannot import name 'six' from 'django.utils' due to line 13 in axes==4.5.4
(cherry picked from commit 73066da0013373c18808adde115bbb52c75fab39)