[core] Avoid exception in 500 stack printing view with Python 2
https://docs.python.org/2/library/traceback.html

  File "/opt/cloudera/parcels/CDH-7.2.9-1.cdh7.2.9.p1.14166188/lib/hue/desktop/core/src/desktop/views.py", line 463, in serve_500_error
    tb = '\n'.join(tb.format())
AttributeError: 'list' object has no attribute 'format'

(cherry picked from commit 8544bff41a3c4d1dc6f3bf9eb11d6780e0e3ffcf)