HUE-9112 [lib] Avoid unicode decode error in Resource logging
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 110: ordinal not in range(128)
(cherry picked from commit 3edbef9e0dae24924aecab1b83c7e1100b541eb4)

Change-Id: I7134ce8f7e3231dace21c1dd607a5a69d9056102