[jb] Avoid javascript error when application does not have a valid time
In particular having a non numeric for startedTime will create a
TypeError: Cannot read property '1' of null