HUE-5112 [oozie] Protect against invalid parameter values in document action
e.g.
  File "/home/romain/projects/hue/apps/oozie/src/oozie/models2.py", line 395, in find_parameters
    name, val = param['value'].split('=')
ValueError: need more than 1 value to unpack

(cherry picked from commit 89fb005d2243e2f20c9896a79e90dd244081d2a9)