HUE-9450 [jb] Avoid failure to start when app is blacklisted
  File "/usr/share/hue/desktop/core/src/desktop/urls.py", line 50, in <module>
    from desktop.configuration import api as desktop_configuration_api
  File "/usr/share/hue/desktop/core/src/desktop/configuration/api.py", line 32, in <module>
    from notebook.connectors.hiveserver2 import HiveConfiguration, ImpalaConfiguration
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/hiveserver2.py", line 79, in <module>
    from jobbrowser.views import get_job
  File "/usr/share/hue/apps/jobbrowser/src/jobbrowser/views.py", line 64, in <module>
    from jobbrowser.api import get_api, ApplicationNotRunning, JobExpired
  File "/usr/share/hue/apps/jobbrowser/src/jobbrowser/api.py", line 38, in <module>
    from jobbrowser.yarn_models import Application, YarnV2Job, Job as YarnJob, KilledJob as KilledYarnJob, Container, SparkJob
  File "/usr/share/hue/apps/jobbrowser/src/jobbrowser/yarn_models.py", line 44, in <module>
    from jobbrowser.models import format_unixtime_ms
  File "/usr/share/hue/apps/jobbrowser/src/jobbrowser/models.py", line 85, in <module>
    class HiveQuery(models.Model):
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/db/models/base.py", line 118, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class jobbrowser.models.HiveQuery doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

(cherry picked from commit 7b46ca50acaa490ba9e993f9951d3e2ed5e508cf)