AttributeError: module 'django.db.models.fields' has no attribute 'FieldDoesNotExist'
(cherry picked from commit d00f3f17f6c0615bb86f0482fafd44524f22ff2c)