HUE-9197 [abfs] Add missing interface attributes
Light code formatting.
To avoid 500 on system with only abfs:

[17/Mar/2020 12:40:49 -0700] middleware   INFO     Processing exception: 'ABFS' object has no attribute 'supergroup': Traceback (most recent call last):
  File "/home/romain/projects/hue/build/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/romain/projects/hue/apps/filebrowser/src/filebrowser/views.py", line 215, in view
    return listdir_paged(request, path)
  File "/home/romain/projects/hue/apps/filebrowser/src/filebrowser/views.py", line 528, in listdir_paged
    is_fs_superuser = _is_hdfs_superuser(request)
  File "/home/romain/projects/hue/apps/filebrowser/src/filebrowser/views.py", line 1437, in _is_hdfs_superuser
    return request.user.username == request.fs.superuser or request.user.groups.filter(name__exact=request.fs.supergroup).exists()
  File "/home/romain/projects/hue/desktop/core/src/desktop/lib/fs/proxyfs.py", line 56, in __getattr__
    return getattr(object.__getattribute__(self, "_default_fs"), item)
AttributeError: 'ABFS' object has no attribute 'supergroup'

(cherry picked from commit 226a3a80fb252225a348c10c20897d5af0525091)

Change-Id: I03703a2b84509610192013898dad2cd2db499b73