CDPD-40712: [jwt] Bump djangorestframework-simplejwt to 5.2.0 (#2875)
- Required for error: AttributeError: 'str' object has no attribute 'decode'
- This error comes when trying to use Hue public API via Hue's JWT access token.
- Version 4.7+ contains the fix so we upgraded to the latest. This was required because we upgraded PyJWT to 2.4.0 due to CVE.

(cherry picked from commit 09999a1560978c5252662a15f57d2e5ae63b9ace)
(cherry picked from commit 0745bce780e13c1098042bc86d2cb945cea5f180)
Change-Id: Ib8d02162ed94129983833001fa96a07012e56e96
(cherry picked from commit 937514dd7e971885f8e8696af4dfce7ae5985b5a)