HUE-8737 [py3] Use desktop lib smart_unicode to not crash admin page
ImportError: cannot import name 'smart_unicode'
(cherry picked from commit 0992616ffa4563dbcc3bf7c942d5ff9b3815374f)

Change-Id: I4925342066f166345e473bf20402e15bec2634ca