[Django 3.0] ImportError: cannot import name 'render_to_response' from 'django.shortcuts'
(cherry picked from commit d111ce8bb5c776a5984f1c228d43366553e8a51a)