[jwt] Bump djangorestframework-simplejwt to 5.2.0
- Required for error: AttributeError: 'str' object has no attribute 'decode'
- This error comes when trying to use Hue public API via Hue's JWT access token.
- Version 4.7+ contains the fix so we upgraded to the latest. This was required because we upgraded PyJWT to 2.4.0 due to CVE.