CDPD-65034: Check csrf to see if it has value before setting it up (#3592)
Internal Jira: CDPD-65034

Seeing the exception:
thrift_util  ERROR    Thrift saw exception (this may be expected).
Traceback (most recent call last):
  File “/opt/cloudera/parcels/CDH-7.1.9-1.cdh7.1.9.p0.44702451/lib/hue/desktop/core/src/desktop/lib/thrift_util.py”, line 522, in wrapper
    ret = res(*args, **kwargs)
  File “/opt/cloudera/parcels/CDH-7.1.9-1.cdh7.1.9.p0.44702451/lib/hue/apps/beeswax/gen-py/TCLIService/TCLIService.py”, line 255, in decorate
    trans_client.setCustomHeaders({‘X-CSRF-TOKEN’: csrf})
TypeError: ‘NoneType’ object is not callable

and

  File “/opt/cloudera/parcels/CDH-7.1.9-1.cdh7.1.9.p0.44702451/lib/hue/desktop/core/src/desktop/lib/thrift_util.py”, line 522, in wrapper
    ret = res(*args, **kwargs)
  File “/opt/cloudera/parcels/CDH-7.1.9-1.cdh7.1.9.p0.44702451/lib/hue/apps/beeswax/gen-py/TCLIService/TCLIService.py”, line 233, in decorate
    trans_client.setCustomHeaders({‘X-Forwarded-For’: xff})
TypeError: ‘NoneType’ object is not callable

(cherry picked from commit cc7b6311aebcb18bec80a983601cf43a45cae371)
(cherry picked from commit 7463d4b0adfb834ff4bee870b2b1d7d21bae0d0d)
Change-Id: Ic1ca3eea72e7110c9ce165d13cedd92ba21dff0a