HUE-9106 [core] Compare Python version by tuple and not string
If not in Python 3:
TypeError: '>=' not supported between instances of 'str' and 'tuple'

(cherry picked from commit fae76907ced57113dabeb354edff9707f5599b00)

Change-Id: I603cd4134107ce08a0b773872fd6f7827a2cf6ab