[Django 3.0] ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding'
(cherry picked from commit 5b4ca5da2cf11c55903a25346f66db2a703d3961)