HUE-7402 [core] Truncate SEARCH Column in Document2 for Oracle database
  Searching saved documents in Oracle returns following error:
    DatabaseError: ORA-06502: PL/SQL: numeric or value error: character string buffer too small
  This is caused by DBMS_LOB.SUBSTR(%s, 4000) in Django framework django/db/backends/oracle/base.py
  Django has a ticket for this issue but unfixed: https://code.djangoproject.com/ticket/11580.
  Buffer size 4000 limit the length of field equals or less than 2000 characters.

(cherry picked from commit 417a9cc9d4bf23e390fe0cddc779d223c10fbe40)