[core] Call super() in HueRemoteUserMiddleware
After deploying Hue 4.9 I got the following error:

AttributeError: 'HueRemoteUserMiddleware' object has no attribute 'get_response'

I have Hue set up with
backend=desktop.auth.backend.RemoteUserDjangoBackend, httpd is in front
of it with Apereo Cas and passes the username as part of a remote
header.

HueRemoteUserMiddleware inherits from RemoteUserMiddleware, that with
Django 2.x inherits from MiddlewareMixin, that requires get_response.

(cherry picked from commit 9e5039cb8b949894d00c01cf6624185c8cb6ca7c)